packages:
  - 'packages/*'

# Configuración de pnpm workspaces
# Permite hoist de dependencias compartidas
hoist-pattern:
  - '*'

# Configuración de resolución de dependencias
resolution-mode: 'highest'

# Configuración de caché
store-dir: ~/.pnpm-store

# Configuración de logs
loglevel: warn

# Configuración de peer dependencies
auto-install-peers: true
strict-peer-dependencies: false

# Configuración de scripts
enable-pre-post-scripts: true
